# Generated by Django 4.1.1 on 2022-10-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='course_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory_name', models.CharField(max_length=100)),
                ('subcategory_status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='course.course_category')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Subcategory',
                'verbose_name_plural': 'Course Subcategories',
                'db_table': 'course_subcategory',
            },
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('assamese', 'Assamese'), ('bengali', 'Bengali'), ('gujarati', 'Gujarati'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('marathi', 'Marathi'), ('odia', 'Odia'), ('punjabi', 'Punjabi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('urdu', 'Urdu'), ('arabic', 'Arabic'), ('bodo', 'Bodo'), ('chinese', 'Chinese'), ('dogri', 'Dogri'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('kashmiri', 'Kashmiri'), ('konkani', 'Konkani'), ('maithili', 'Maithili'), ('manipuri', 'Manipuri'), ('nepali', 'Nepali'), ('persian', 'Persian'), ('russian', 'Russian'), ('santhali', 'Santhali'), ('sindhi', 'Sindhi'), ('spanish', 'Spanish'), ('tibetan', 'Tibetan'), ('sanskrit', 'Sanskrit'), ('accountancy', 'Accountancy'), ('agriculture', 'Agriculture'), ('anthropology', 'Anthropology'), ('art_education_sculpture', 'Art Education Sculpture'), ('biology', 'Biology'), ('business_studies', 'Business Studies'), ('chemistry', 'Chemistry'), ('computer_science', 'Computer Science'), ('economics_business_economics', 'Economics/Business Economics'), ('engineering_graphics', 'Engineering Graphics'), ('entrepreneurship', 'Entrepreneurship'), ('environmental_studies', 'Environmental Studies'), ('general_test', 'General Test'), ('geography', 'Geography'), ('history', 'History'), ('home_science', 'Home Science'), ('knowledge_tradition_practices_india', 'Knowledge Tradition – Practices India'), ('languages_ia_ib', 'Languages (IA & IB)'), ('legal_studies', 'Legal Studies'), ('mass_media_mass_communication', 'Mass Media/ Mass Communication'), ('mathematics', 'Mathematics'), ('performing_arts', 'Performing Arts'), ('physical_education', 'Physical Education'), ('physics', 'Physics'), ('political_science', 'Political Science'), ('psychology', 'Psychology'), ('sanskrit', 'Sanskrit'), ('sociology', 'Sociology'), ('teaching_aptitude', 'Teaching Aptitude')], max_length=100, unique=True, verbose_name='Course Name')),
                ('course_code', models.CharField(blank=True, max_length=100, null=True)),
                ('course_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Course Description')),
                ('text_booklets', models.IntegerField(blank=True, default=0, null=True)),
                ('videos_lectures', models.IntegerField(blank=True, default=0, null=True)),
                ('total_tests', models.IntegerField(blank=True, default=0, null=True)),
                ('course_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('course_duration_unit', models.CharField(blank=True, choices=[('hour', 'Hour'), ('hours', 'Hours'), ('day', 'Day'), ('days', 'Days'), ('week', 'Week'), ('weeks', 'Weeks'), ('month', 'Month'), ('months', 'Months'), ('year', 'Year'), ('years', 'Years')], default='hours', max_length=10, null=True)),
                ('paper_pattern', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Paper Pattern')),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('negative_marking', models.IntegerField(blank=True, default=0, null=True)),
                ('course_status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('course_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='course.course_category', verbose_name='Course Category')),
                ('course_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_subcategory', to='course.course_subcategory', verbose_name='Course Subcategory')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='study_material.syllabus')),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
    ]
