SUBJECT_CHOICES = [
    # English, Hindi, Assamese, Bengali, Gujarati, Kannada, Malayalam, Marathi, Odia, Punjabi, Tamil, Telugu, Urdu
    ('english', 'English'),
    ('hindi', 'Hindi'),
    ('assamese', 'Assamese'),
    ('bengali', 'Bengali'),
    ('gujarati', 'Gujarati'),
    ('kannada', 'Kannada'),
    ('malayalam', 'Malayalam'),
    ('marathi', 'Marathi'),
    ('odia', 'Odia'),
    ('punjabi', 'Punjabi'),
    ('tamil', 'Tamil'),
    ('telugu', 'Telugu'),
    ('urdu', 'Urdu'),
#     Arabic, Bodo, Chinese, Dogri, French, German, Italian, Japanese, Kashmiri, Konkani, Maithili, Manipuri, Nepali,
# Persian, Russian, Santhali, Sindhi, Spanish, Tibetan, Sanskrit,
    ('arabic', 'Arabic'),
    ('bodo', 'Bodo'),
    ('chinese', 'Chinese'),
    ('dogri', 'Dogri'),
    ('french', 'French'),
    ('german', 'German'),
    ('italian', 'Italian'),
    ('japanese', 'Japanese'),
    ('kashmiri', 'Kashmiri'),
    ('konkani', 'Konkani'),
    ('maithili', 'Maithili'),
    ('manipuri', 'Manipuri'),
    ('nepali', 'Nepali'),
    ('persian', 'Persian'),
    ('russian', 'Russian'),
    ('santhali', 'Santhali'),
    ('sindhi', 'Sindhi'),
    ('spanish', 'Spanish'),
    ('tibetan', 'Tibetan'),
    ('sanskrit', 'Sanskrit'),
    ('accountancy', 'Accountancy'),
    ('agriculture', 'Agriculture'),
    ('anthropology', 'Anthropology'),
    ('art_education_sculpture', 'Art Education Sculpture'),
    ('biology', 'Biology'),
    ('business_studies', 'Business Studies'),
    ('chemistry', 'Chemistry'),
    ('computer_science', 'Computer Science'),
    ('economics_business_economics', 'Economics/Business Economics'),
    ('engineering_graphics', 'Engineering Graphics'),
    ('entrepreneurship', 'Entrepreneurship'),
    ('environmental_studies', 'Environmental Studies'),
    ('general_test', 'General Test'),
    ('geography', 'Geography'),
    ('history', 'History'),
    ('home_science', 'Home Science'),
    ('knowledge_tradition_practices_india', 'Knowledge Tradition – Practices India'),
    ('languages_ia_ib', 'Languages (IA & IB)'),
    ('legal_studies', 'Legal Studies'),
    ('mass_media_mass_communication', 'Mass Media/ Mass Communication'),
    ('mathematics', 'Mathematics'),
    ('performing_arts', 'Performing Arts'),
    ('physical_education', 'Physical Education'),
    ('physics', 'Physics'),
    ('political_science', 'Political Science'),
    ('psychology', 'Psychology'),
    ('sanskrit', 'Sanskrit'),
    ('sociology', 'Sociology'),
    ('teaching_aptitude', 'Teaching Aptitude'),
]

SECTION_CHOICES = [
    ('about', 'About'),
    ('why_choose_us', 'Why Choose Us'),
    ('courses', 'Courses'),
    ('testimonials', 'Testimonials'),
    ('features', 'Features'),
    ('faqs', 'FAQs'),
    ('contact', 'Contact'),
]

UNIT_CHOICES = [
    ('hour', 'Hour'),
    ('hours', 'Hours'),
    ('day', 'Day'),
    ('days', 'Days'),
    ('week', 'Week'),
    ('weeks', 'Weeks'),
    ('month', 'Month'),
    ('months', 'Months'),
    ('year', 'Year'),
    ('years', 'Years'),
]