# Generated by Django 4.1.1 on 2022-10-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(choices=[('mentorspanel', 'Mentors Panel'), ('eminentfaculties', 'Eminent Faculties'), ('executivecommittee', 'Executive Committee'), ('foundingmembers', 'Founding Members'), ('ourassociates', 'Our Associates'), ('ourpartners', 'Our Partners'), ('ourstudents', 'Our Students'), ('ouralumni', 'Our Alumni'), ('ourvolunteers', 'Our Volunteers'), ('oursponsors', 'Our Sponsors'), ('ourfellowshippers', 'Our Fellowshippers'), ('ourcontributors', 'Our Contributors'), ('ourcommunity', 'Our Community')], max_length=100)),
                ('team_member_name', models.CharField(max_length=100)),
                ('team_member_designation', models.CharField(max_length=100)),
                ('team_member_image', models.ImageField(upload_to='team_images')),
                ('team_member_description', models.TextField()),
                ('team_member_status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
            },
        ),
    ]
